
#################################################
### THIS FILE WAS AUTOGENERATED! DO NOT EDIT! ###
#################################################
# file to edit: dev_nb/utils.ipynb
import numpy as np
import matplotlib.pyplot as plt
from PIL import Image

def load_image(Path): return np.array(Image.open(Path))

def plot_sample(lr, hr):
    plt.figure(figsize = (20, 10))

    images = [lr, hr]
    titles = ['LR', f'SR (x{lr.shape[0] // hr.shape[0]})']

    for i, (img, title) in enumerate(zip(images, titles)):
        plt.subplot(1, 2, i+1)
        plt.imshow(img)
        plt.title(title)
        plt.xticks([])
        plt.yticks([])